language: c

python:
  - "2.7"

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    # - compiler: ": Lua52"
    #   env: LUA="lua 5.2"
    # - compiler: ": Lua53"
    #   env: LUA="lua 5.3"
    # - compiler: ": LuaJIT20"
    #   env: LUA="luajit 2.0"
    # - compiler: ": LuaJIT21"
    #   env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make rockspecs/multirequests-scm-0.rockspec

script:
  - lua examples/basic.lua

notifications:
  email:
    on_success: change
    on_failure: always
